name: Validate Jira number in commit message
on: push

jobs:
  validate_commit_message:
    runs-on: ubunturunner
    steps:
    - uses: actions/checkout@v2
    - name: Validate commit message
      run: |
        commit_message=$(git log -1 --pretty=format:%s)
        regex='^[A-Z]{3,}-[0-9]{5,}+.*$'
        echo "commit message is:$commit_message"
        if ! [[ $commit_message =~ $regex ]]; then
          echo "Commit message does not start with a Jira number."
          exit 1
        fi
